name: universe
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  shared_preferences: ^2.2.3
  awesome_notifications: ^0.10.1
  crypto: ^3.0.3
  http: ^1.5.0
  intl: ^0.20.2
  url_launcher: ^6.3.2
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  permission_handler: ^11.3.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - img/logouniverse.png
    - img/profile.jpg
    - img/quiz.png 
    - img/1.png
    - img/2.png
    - img/3.png
    - img/zoom.png
    - img/harvard.jpg
    - img/nus.jpg
    - img/heidel.jpg
    - img/peta.jpeg


flutter_launcher_icons:
  android: true
  ios: false
  image_path: "img/logouniverse.png"
